import { animate, inView } from 'motion';
import * as THREE from 'three';
import lottie from 'lottie-web';
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduce.matches;const toggle=document.querySelector('#motion-toggle');
document.querySelector('#year').textContent=new Date().getFullYear();
const lottieData={v:'5.7.4',fr:30,ip:0,op:120,w:240,h:180,nm:'Signal',ddd:0,assets:[],layers:[0,1,2].map((n)=>({ddd:0,ind:n+1,ty:4,nm:'Signal ring',sr:1,ks:{o:{a:0,k:100},r:{a:0,k:0},p:{a:0,k:[120,90,0]},a:{a:0,k:[0,0,0]},s:{a:1,k:[{t:0,s:[40+n*22,40+n*22,100],e:[85+n*20,85+n*20,100],i:{x:[.67,.67,.67],y:[1,1,1]},o:{x:[.33,.33,.33],y:[0,0,0]}},{t:60,s:[85+n*20,85+n*20,100],e:[40+n*22,40+n*22,100],i:{x:[.67,.67,.67],y:[1,1,1]},o:{x:[.33,.33,.33],y:[0,0,0]}},{t:120,s:[40+n*22,40+n*22,100]}]}},shapes:[{ty:'el',p:{a:0,k:[0,0]},s:{a:0,k:[100,100]},nm:'Ring'},{ty:'st',c:{a:0,k:[1,.65,.3,1]},o:{a:0,k:85-n*20},w:{a:0,k:2},lc:2,lj:2}],ip:0,op:120,st:0,bm:0}))};
const signal=lottie.loadAnimation({container:document.querySelector('#signal'),renderer:'svg',loop:true,autoplay:!paused,animationData:lottieData});
if(!reduce.matches){inView('.reveal',el=>{animate(el,{opacity:[0,1],y:[24,0]},{duration:.65,ease:[.2,.7,.2,1]});},{margin:'0px 0px -35px 0px'});}
const ambient=document.querySelector('.ambient-video');let filmVisible=false;const observer=new IntersectionObserver(([entry])=>{filmVisible=entry.isIntersecting;if(filmVisible&&!paused){if(!ambient.src)ambient.src=ambient.dataset.src;ambient.play().catch(()=>{});}else ambient.pause();},{rootMargin:'120px'});observer.observe(ambient);
function syncMotion(){document.body.classList.toggle('paused',paused);toggle.setAttribute('aria-pressed',String(paused));toggle.textContent=paused?'▶ Resume motion':'Ⅱ Pause motion';paused?signal.pause():signal.play();if(paused)ambient.pause();else if(filmVisible){if(!ambient.src)ambient.src=ambient.dataset.src;ambient.play().catch(()=>{});}}
toggle.addEventListener('click',()=>{paused=!paused;syncMotion();});reduce.addEventListener('change',e=>{paused=e.matches;syncMotion();});syncMotion();
document.querySelector('#play-film').addEventListener('click',()=>{ambient.pause();observer.disconnect();const frame=document.createElement('iframe');frame.src='https://www.youtube.com/embed/eN1MThatGA4?si=h49fY26ghk_cbCaL&autoplay=1';frame.title='Sudarshan AI Labs featured YouTube film';frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;document.querySelector('#youtube-slot').append(frame);document.querySelector('.film-overlay').hidden=true;frame.focus();});
try{const canvas=document.querySelector('#scene');const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,0,8);scene.add(new THREE.AmbientLight(0xffd5ac,2));const key=new THREE.DirectionalLight(0xffbc76,5);key.position.set(3,4,5);scene.add(key);const rim=new THREE.DirectionalLight(0x8ea6ff,3);rim.position.set(-3,-1,2);scene.add(rim);const center=new THREE.PointLight(0xff6b16,30);center.position.set(0,0,2);scene.add(center);const group=new THREE.Group();scene.add(group);const material=new THREE.MeshPhysicalMaterial({color:0xb66c2a,metalness:.85,roughness:.2,clearcoat:1,clearcoatRoughness:.15});const knot=new THREE.Mesh(new THREE.TorusKnotGeometry(1.22,.36,180,32,2,3),material);group.add(knot);const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(.48,0),new THREE.MeshPhysicalMaterial({color:0xffd095,metalness:.5,roughness:.15,emissive:0x8a3204,emissiveIntensity:.7}));group.add(inner);const dustGeometry=new THREE.BufferGeometry();const particles=new Float32Array(120*3);for(let i=0;i<particles.length;i++)particles[i]=(Math.random()-.5)*8;dustGeometry.setAttribute('position',new THREE.BufferAttribute(particles,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({color:0xd49751,size:.018,transparent:true,opacity:.6}));scene.add(dust);let mouseX=0,mouseY=0;canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouseX=(e.clientX-r.left)/r.width-.5;mouseY=(e.clientY-r.top)/r.height-.5;});canvas.addEventListener('pointerleave',()=>{mouseX=0;mouseY=0;});function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);resize();let visible=true;new IntersectionObserver(([e])=>{visible=e.isIntersecting}).observe(canvas);const clock=new THREE.Clock();let t=0;function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.05);if(document.hidden||!visible)return;if(!paused){t+=dt;group.rotation.y=t*.17+mouseX*.5;group.rotation.x=.3+Math.sin(t*.23)*.18+mouseY*.3;group.rotation.z=-.15;group.position.y=Math.sin(t*.6)*.09;inner.rotation.y=-t*.5;dust.rotation.y=t*.018;}renderer.render(scene,camera);}render();document.querySelector('.sculpture').classList.add('scene-ready');canvas.addEventListener('webglcontextlost',()=>{document.querySelector('.sculpture').classList.remove('scene-ready');});}catch(e){console.warn('3D rendering unavailable; showing static fallback.');}
